### ISSUE TITLE
pass close fails when residing in the .password-store directory

### ISSUE THREAD

**Issue by thewaywest** [roddhjav/pass-tomb#13] opened 2017-12-28 08:06 UTC
... not a bug, but an inconvenience:

- open the tomb
- move to the .password-store directory to do some manual work on the gpg files/folders
- finish the work and close the tomb **without changing directory out of the store**
- close fails and no error message tells me I am interfering with the close action

resolution: added a line to the close bash script to perform a "cd ~" if I am currently located anywhere in the .password-store folder tree.

**Comment by roddhjav** [comment] 2017-12-28 10:30
It's a feature, not a bug. It prevents the tomb to close itself if it is in use.

However, I can do the following:
1. Improve the error message.
2. Add a force option that `slam` the tomb even if it is in use.

**Comment by roddhjav** [comment] 2018-04-01 14:13
Fixed with pass-tomb 1.1

**Closed by roddhjav** 2018-04-01 14:13 UTC
